### ISSUE TITLE
Consider a Kali Linux dev container

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/hapi-lab#1]
## Tasks
- [x] Try dev container from kali-rolling.
- [x] Perform apt update/upgrade per author instructions.
- [x] Install git, python3, and golang per author instructions.

## Notes
* https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers
* See devcontainers spec at https://containers.dev/implementors/spec/.
* See default Linux image at https://github.com/devcontainers/images/tree/main/src/universal.
* Browse predefined dev container images at https://github.com/devcontainers/images/tree/main/src.
  * Note, `base-*` images might be worth reviewing if we decide to make a `base-kali`.
  * Also, anaconda Dockerfile seems worth reviewing too.
* Interesting, see more about features at https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#adding-additional-features-to-your-devcontainerjson-file.
  * Especially the feature contribs list at https://containers.dev/features.
  * Maybe start with the GH (and other) CLI.
  * The gitleaks and postman features catch the eye too.
