### ISSUE TITLE
Consider Docker for Kali dev container

### ISSUE THREAD

**Issue by jelaiw** [jelaiw/hapi-lab#4]
## Tasks
- [x] Try docker-in-docker feature.
- [x] Try docker-outside-of-docker feature.
- [x] Try Kali `docker.io` package.

## Links
* https://www.kali.org/docs/containers/installing-docker-on-kali/
* https://github.com/devcontainers/features/tree/main/src/docker-in-docker
* https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker
